# Site settings
title: Data Science for Social Good 2015
email: arokem@gmail.com
description: "#DSSG2015 @uwescience"
#baseurl: "http://uwescience.github.io/DSSG2015"
baseurl: "http://yunhaolucky.github.io/DSSG_sidewalk"
#url: "http://uwescience.github.io/DSSG2015" 
url: "http://yunhaolucky.github.io/DSSG_sidewalk"
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
