# Site settings
title: Data Science for Social Good 2015
email: arokem@gmail.com
description: "#DSSG2015 @uwescience"
baseurl: "http://uwescience.github.io/DSSG2015" 
url: "http://uwescience.github.io/DSSG2015" 
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
